server:
  port: 8761
  
eureka:
  instance:
    hostname: service-registry
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
