server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_registration
    username: root
    password: Rgukt@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
      host: smtp.gmail.com
      username: invaliduser409@gmail.com
      password: Rgukt@123
      port: 587
      properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
  # main:
  #   allow-bean-definition-overriding: true
## Oauth2 related
  # security:
  #   oauth2:
  #     client:
  #       registration:
  #         api-client-oidc:
  #           provider: spring
  #           client-id: api-client
  #           client-secret: secret
  #           authorization-grant-type: authorization_code
  #           redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
  #           scope: openid
  #           client-name: api-client-oidc
  #         api-client-authorization-code:
  #           provider: spring
  #           client-id: api-client
  #           client-secret: secret
  #           authorization-grant-type: authorization_code
  #           redirect-uri: "http://127.0.0.1:8080/authorized"
  #           scope: api.read
  #           client-name: api-client-authorization-code
  #       provider:
  #         spring:
  #           issuer-uri: http://auth-server:9000
jwt:
  secret: secretkey123