server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# management:
#   tracing:
#     sampling:
#       probability: 1.0

# spring:
#   zipkin:
#     base-url: http://127.0.0.1:9411/